"""Module for generating PowerPoint presentations."""

from pptx import Presentation
from pptx.util import Inches, Pt


def create_title_slide(prs: Presentation, title: str, subtitle: str = "") -> None:
    """Create a title slide for the presentation."""
    slide_layout = prs.slide_layouts[0]  # Title slide layout
    slide = prs.slides.add_slide(slide_layout)
    
    title_shape = slide.shapes.title
    subtitle_shape = slide.placeholders[1]
    
    title_shape.text = title
    subtitle_shape.text = subtitle


def create_content_slide(prs: Presentation, title: str, bullet_points: list, notes: str = "") -> None:
    """Create a content slide with title and bullet points."""
    slide_layout = prs.slide_layouts[1]  # Title and Content layout
    slide = prs.slides.add_slide(slide_layout)
    
    # Set title
    title_shape = slide.shapes.title
    title_shape.text = title
    
    # Set content
    content_shape = slide.placeholders[1]
    text_frame = content_shape.text_frame
    
    for i, point in enumerate(bullet_points):
        if i == 0:
            text_frame.text = point
        else:
            p = text_frame.add_paragraph()
            p.text = point
            p.level = 0
    
    # Add speaker notes if provided
    if notes:
        notes_slide = slide.notes_slide
        notes_slide.notes_text_frame.text = notes


def create_section_slide(prs: Presentation, title: str) -> None:
    """Create a section header slide."""
    slide_layout = prs.slide_layouts[2]  # Section header layout
    slide = prs.slides.add_slide(slide_layout)
    
    title_shape = slide.shapes.title
    title_shape.text = title


def generate_pptx(presentation_data: dict, output_path: str) -> str:
    """
    Generate a PowerPoint file from the presentation data.
    
    Args:
        presentation_data: Dictionary containing title and slides.
        output_path: Path where the PPTX file should be saved.
        
    Returns:
        The path to the generated PPTX file.
    """
    prs = Presentation()
    
    # Set slide dimensions (16:9 widescreen)
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    
    # Get presentation title
    main_title = presentation_data.get('title', 'Untitled Presentation')
    
    # Create title slide
    create_title_slide(prs, main_title, "Generated by AI PowerPoint Generator")
    
    # Create content slides
    slides = presentation_data.get('slides', [])
    
    for slide_data in slides:
        slide_title = slide_data.get('title', 'Untitled Slide')
        content = slide_data.get('content', [])
        notes = slide_data.get('notes', '')
        
        if isinstance(content, str):
            content = [content]
        
        create_content_slide(prs, slide_title, content, notes)
    
    # Save the presentation
    prs.save(output_path)
    
    return output_path
